refactor(version): refactor harborcluster version to v1alpha1
goharbor/harbor-cluster-operator pull request #231
Opened 2020-10-13 12:39 UTC by wangcanfengxs

CLOSE #228

Signed-off-by: wangcanfeng <wangcanfeng@corp.netease.com>

2020-10-13 15:15 UTC, bitsf requested changes

2020-10-13 15:15 UTC, bitsf commented on Dockerfile
> +COPY apis api/
COPY apis/ apis/

2020-10-14 02:44 UTC, bitsf approved these changes

2020-10-14 04:13 UTC, Ghostbaby approved these changes
lgtm

2020-10-14 05:59 UTC, merged